project:
  type: website

website:
  title: "Vanuella"
  description: "Discover the musical universe that creates the bridge between music and love through the soul" # Added Description
  image: images/vanu-logo-150px.png
  favicon: images/vanu-favicon.png
  twitter-card:
    site: "@Vanuella"
  open-graph: true
  site-url: https://www.vanuella.com/
  repo-url: https://github.com/vanuella/vanuella.github.io
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    background: "#8d4f9e"
    logo: images/vanu-logo-150px.png
    logo-alt: "Vanuella brand"
    title: false
    collapse-below: lg
    right:
      - text: "Events"
        href: events/index.qmd
      - text: "Songs"
        href: songs/index.qmd
      - text: "Videos"
        href: videos/index.qmd
      - text: "Media"
        href: media/index.qmd
      - text: "Gallery"
        href: gallery/index.qmd
      - icon: github
        href: https://github.com/vanuella
      - icon: twitter
        href: https://twitter.com/vanuella # Moved to page-footer
  page-footer:
    left: "Copyright © 2025 Vanuella. All rights reserved."
    right:
      - icon: github
        href: https://github.com/vanuella
      - icon: twitter
        href: https://twitter.com/vanuella


format:
  html:
    theme: [default, vanuella.scss]
    css: 
      - vanuella.css

execute:
  freeze: auto