project:
  type: website

website:
  title: "Vanuella"
  description: "Discover the musical universe that creates the bridge between music and love through the soul"
  image: images/vanu-ai-logo-150px.png
  favicon: images/vanu-flavicon.png
  twitter-card:
    site: "@VanuellaSing"
  open-graph: true
  site-url: https://www.vanuella.com/
  repo-url: https://github.com/vanuella/vanuella.github.io
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    background: "#8d4f9e"
    logo: images/vanu-logo-150px.png
    logo-alt: "Vanuella brand"
    title: false
    collapse-below: lg
    right:
      # Social media icons
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61575253262807  # Update with your actual Facebook URL
      - icon: instagram
        href: https://instagram.com/vanuella
      - icon: spotify
        href: https://open.spotify.com/artist/4GziIZh9D15WSH0dV0Zobs
      - icon: twitter
        href: https://twitter.com/VanuellaSing
      - icon: youtube
        href: https://youtube.com/@VanuellaSing
      
      # Existing navigation items (optional - keep if needed)
      - text: "Events"
        href: events/index.qmd
      - text: "Songs"
        href: songs/index.qmd
      - text: "Videos"
        href: videos/index.qmd
      - text: "Media"
        href: media/index.qmd
      - text: "Gallery"
        href: gallery/index.qmd
      - icon: mic
        href: events/about.qmd

  page-footer:
    left: "Copyright © 2025 Vanuella. All rights reserved."
    right:
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61575253262807  # Update with your actual Facebook URL
      - icon: instagram
        href: https://instagram.com/vanuella
      - icon: spotify
        href: https://open.spotify.com/artist/4GziIZh9D15WSH0dV0Zobs
      - icon: twitter
        href: https://twitter.com/VanuellaSing
      - icon: youtube
        href: https://youtube.com/@VanuellaSing

format:
  html:
    theme: [default, vanuella.scss]
    css: 
      - vanuella.css

execute:
  freeze: auto
