---
title: "Vanuella"
page-layout: article
title-block-banner: true
---

# Meet Our Team 

At Vanuella, our strength lies in our diverse team of data scientists, analysts, and industry experts. Each team member brings a unique set of skills and experiences to help solve your data challenges.

## Music

::: {.grid}

::: {.g-col-6}

### Vannella Watt

**Artiste & Chief Data Singer**

On l'a surnommée "l’Edith Piaf du Pacifique", "l’Aigle noir à la voix d’ange" ou encore la "Diva du Pacifique". Stéphanie-Vanuella Watt, née en France et élevée au Vanuatu puis en Nouvelle-Calédonie dès l’âge de 6 mois, incarne le métissage culturel et artistique. Fille du célèbre sculpteur mélanésien Emmanuel Watt et d’une mère italienne pianiste, elle baigne dans un univers artistique depuis son plus jeune âge. Dès 10 ans, elle monte sur scène et commence à se produire, marquant le début d’une carrière exceptionnelle.

Vanuella a parcouru le Pacifique, s’est rendue en Californie et a passé plusieurs années en France, où elle a réalisé son premier album, Revoir mes îles. Elle a notamment enchanté le public parisien pendant plusieurs mois au Don Camilo. Artiste accomplie, elle a représenté la Nouvelle-Calédonie au festival mondial de la musique. Son timbre de voix ensorceleur a séduit un producteur français rencontré au Midem de Cannes, qui lui a proposé de produire son album Soleil, soleil. Ce titre phare, largement apprécié en Nouvelle-Calédonie, a propulsé Vanuella au sommet de la célébrité dans le Pacifique Sud.

Vanuella est bien plus qu’une chanteuse : elle est une ambassadrice culturelle. Elle promeut la chanson française, anglaise, italienne, espagnole et bien d’autres à travers le Pacifique, incarnant l’amour du monde et le métissage des cultures. Elle maîtrise avec virtuosité des styles variés, interprétant des titres de variété, jazz, salsa et zouk avec une grâce incomparable.

Aujourd’hui, Vanuella continue de captiver son public en Nouvelle-Calédonie et au-delà. Partout où elle se produit, elle rassemble les foules grâce à sa musique métissée, reflet de la diversité culturelle de son pays. Son charisme naturel, sa voix envoûtante et son interprétation pleine d’émotion transpercent l’âme de son auditoire, faisant de chaque concert une expérience inoubliable. Vanuella Watt, véritable icône du Pacifique, continue de rayonner par son talent et son amour pour les arts.

:::

::: {.g-col-6}
### Miezucu, MBUS

**Chief Data DJ**

Maîtrisant parfaitement R et SQL, j'ai conçu et mis en œuvre des processus ETL automatisés, en utilisant des tables de staging pour optimiser les flux de données. Mon travail s'étend à la réalisation d'audits de licences, au développement de tableaux de bord BI intuitifs, et à l'application d'algorithmes de machine learning pour prédire l'attrition, renforçant ainsi la prise de décision fondée sur les données au sein des équipes internes. Au-delà de mes compétences techniques, je suis passionné par la création de communautés et de plateformes qui mettent en valeur les talents et la créativité.

Aujourd'hui, je mets cette expertise au service de la construction d'une communauté dynamique autour de Vanuella Watt, la voix iconique du Pacifique. En utilisant R et Quarto, je crée des récits dynamiques et axés sur les données qui célèbrent son art et son impact culturel. Ma mission est de créer un écosystème numérique qui non seulement met en lumière sa musique, mais qui engage également ses fans, promeut son travail et assure que son héritage continue d'inspirer. L'histoire de Vanuella est celle d'une fusion culturelle et d'un talent artistique éclatant, et je m'engage à utiliser la technologie pour amplifier sa voix, la connecter à des audiences mondiales et contribuer à son succès durable.

:::

:::

## Our Experts

- **Vanuella**: Artiste & Chief Data Singer
- **Miezucu**: Chief Data DJ

[Join Our Team](contact){.btn .btn-primary}

